export default [
  { label:'ชื่อ Profile', name:'profile_title', type:'text' },
  { label:'ชื่อ - นามสกุล (ภาษาไทย)', name:'input_name', type:'text' },
  { label:'ชื่อ - นามสกุล (ภาษาอังกฤษ)', name:'input_name_en', type:'text' },
  {label:'ชื่อบริษัท/องค์กร (ภาษาไทย)', name:'company_name', type:'text'},  
  {label:'ชื่อบริษัท/องค์กร (ภาษาอังกฤษ)', name:'company_name_en', type:'text'},
  {label:'ตำแหน่งในองค์กร (ภาษาไทย)', name:'title', type:'text'},
  {label:'ตำแหน่งในองค์กร (ภาษาอังกฤษ)', name:'title_en', type:'text'},
  {label:'ที่อยู่ (ภาษาไทย)', name:'address', type:'text'},
  {label:'ที่อยู่ (ภาษาอังกฤษ)', name:'address_en', type:'text'},
  {label:'ลิ้งค์โลเคชั่น', name:'location', type:'text'},
  {label:'อีเมล์ (1)', name:'email1', type:'text'},
  {label:'อีเมล์ (2)', name:'email2', type:'text'},
  {label:'ลิ้งค์เว็บไซต์', name:'website', type:'text'},
  {label:'ลิ้งค์ Line', name:'line', type:'text'},
  {label:'เบอร์โทรศัพท์ (1)', name:'tel1', type:'text'},
  {label:'เบอร์โทรศัพท์ (2)', name:'tel2', type:'text'},
  {label:'เบอร์โทรศัพท์ (3)', name:'tel3', type:'text'},
  {label:'ลิ้งค์ Facebook', name:'facebook', type:'text'},
  {label:'ลิ้งค์ Instagram', name:'instagram', type:'text'},
  {label:'ลิ้งค์ Tiktok', name:'tiktok', type:'text'},
  {label:'ลิ้งค์ Whatsapp', name:'whatsapp', type:'text'},
  {label:'ลิ้งค์ LinkedIn', name:'linkedIn', type:'text'},
  {label:'ไฟล์โลโก้บริษัทหรือภาพอื่นๆที่ต้องการพิมพ์ลงนามบัตร', name:'logo', type:'file'},
  {label:'ไฟล์รูปบุคคลเจ้าของบัตร Profile Picture', name:'avatar', type:'file'}
  
];